### ISSUE TITLE
Price update for Heist gives Error 404

### ISSUE THREAD

**Issue by roerch** [und3rdg/xenontrade#12]
Using xenonTrade 1.2.0 under Linux (Debian testing) and I'm getting error messages after launch stating that the price update failed. I've set the league to Heist, but actually it fails for any setting.

Relevant log entry:
[warn] Failed updating poe.ninja prices, StatusCodeError: 404 - undefined

**Comment by fatino** [comment]
I've seen that it was fixed by in PR. But how to build it? I tried docker image with node 8, node-gyp and it doesn't work
